name: Python application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test_python_app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f Pipfile ]; then 
          pip install pipenv 
          pipenv install --dev --system; 
        fi
       # pip install pytest
       # pip install fastapi
       # pip install unicorn
       # pip install black
       # pip install httpx
         
    - name: Run python script
      run: |
        python src/app.py

    - name: Test with pytest
      run: |
        python -m pytest tests/tests.py --junitxml=test-results.xml
        
    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Python test results
        path: test-results.xml
        reporter: junit
